// Maioria de nomes brasileiros, com alguns internacionais misturados pra reforçar o "todo o mundo"
// da frase da seção. Nomes de exemplo — troque livremente por uma lista real quando tiver uma.
export const NAMES = [
  "Larissa",
  "Gabriel",
  "Beatriz",
  "Lucas",
  "Camila",
  "Rafael",
  "Juliana",
  "Matheus",
  "Fernanda",
  "Bruno",
  "Amanda",
  "Thiago",
  "Isabela",
  "Diego",
  "Priscila",
  "André",
  "Vanessa",
  "Rodrigo",
  "Carla",
  "Felipe",
  "Renata",
  "Gustavo",
  "Sofía",
  "Liam",
  "Yuki",
  "Amara",
  "Noah",
  "Mei",
];
